# Generated by Django 5.1.4 on 2024-12-24 15:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="audio",
            name="name",
            field=models.TextField(default="Image_de12f14f"),
        ),
        migrations.AlterField(
            model_name="image",
            name="name",
            field=models.TextField(default="Image_77077695"),
        ),
        migrations.AlterField(
            model_name="video",
            name="name",
            field=models.TextField(default="Image_bf7deea7"),
        ),
    ]
