# Generated by Django 5.1.4 on 2024-12-24 16:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai", "0002_alter_audio_name_alter_image_name_alter_video_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="audio",
            name="name",
            field=models.TextField(default="Image_aa3f7c6a"),
        ),
        migrations.AlterField(
            model_name="image",
            name="name",
            field=models.TextField(default="Image_12b29e4c"),
        ),
        migrations.AlterField(
            model_name="video",
            name="name",
            field=models.TextField(default="Image_9fe9b245"),
        ),
    ]
